import Head from "next/head";
import SidebarStep from "@/components/SidebarStep";
import FormInputSection from "@/components/FormInputSection";
import { useState } from "react";

export default function Home() {
  const [step, setStep] = useState<number>(1);
  const [formInput, setFormInput] = useState({
    name: "",
    email: "",
    phoneNumber: "",
    planName: "",
    planTime: "monthly",
    planPrice: "",
  });
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <SidebarStep step={step} setStep={setStep} />
        <FormInputSection step={step} setStep={setStep} />
      </main>
    </>
  );
}
